import {DetailTile} from './DetailTile';
import {DateField} from './DateField';
import {PendingSync} from './PendingSync';
import {queueEntry,flushQueue,subscribeSynced} from './offlineSync';
import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,Text,TextInput,View} from 'react-native';
import * as Crypto from 'expo-crypto';
import {rpc} from './client';
type Issue={id:string;urgency:string;description:string;performer_name:string;capture_time:string;server_time:string;resolutions:{id:string;notes:string;server_time:string}[]};
type Compliance={id:string;label:string;due_date:string;lead_days:number[];notify_assigned:boolean;archived:boolean;revision:number;days_remaining:number};
const card={padding:16,borderRadius:14,borderWidth:1,borderColor:'#DFE5DC',backgroundColor:'white',gap:12} as const;
function Button({label,press,disabled=false}:{label:string;press:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={press} style={{padding:14,backgroundColor:'#EAF0E7',borderRadius:10,opacity:disabled?.4:1}}><Text style={{color:'#153C32',fontWeight:'600'}}>{label}</Text></Pressable>;}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <View style={{gap:6}}><Text>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} multiline style={{padding:12,borderWidth:1,borderColor:'#CBD6CC',borderRadius:10,color:'#153C32'}}/></View>;}
export function AssetCare({assetId,admin,writable,captureWritable=writable}:{assetId:string;admin:boolean;writable:boolean;captureWritable?:boolean}){
 const [issues,setIssues]=useState<Issue[]>([]),[items,setItems]=useState<Compliance[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [reporting,setReporting]=useState(false),[description,setDescription]=useState(''),[urgency,setUrgency]=useState('Attention'),[resolution,setResolution]=useState<string|null>(null),[notes,setNotes]=useState('');
 const [editing,setEditing]=useState<Compliance|null|undefined>(undefined),[label,setLabel]=useState(''),[date,setDate]=useState(''),[days,setDays]=useState('30, 7'),[assigned,setAssigned]=useState(false),[archives,setArchives]=useState(false),[remove,setRemove]=useState(false),[expanded,setExpanded]=useState<string|null>(null);
 const ticket=useRef(0),submission=useRef<{id:string;capture:string}|null>(null),resolutionId=useRef<string|null>(null);
 async function load(){const current=++ticket.current;setLoading(true);try{const [a,b]=await Promise.all([rpc<Issue[]>('list_asset_issues',{p_asset:assetId}),rpc<Compliance[]>('list_compliance',{p_asset:assetId})]);if(current===ticket.current){setIssues(a);setItems(b);setError('');}}catch(e){if(current===ticket.current)setError(e instanceof Error?e.message:'Unable to load asset records.');}finally{if(current===ticket.current)setLoading(false);}}
 useEffect(()=>{const stop=subscribeSynced(()=>void load());void load();return()=>{stop();ticket.current++;};},[assetId]);
 async function run(work:()=>Promise<void>,capture=false){if(busy||!(capture?captureWritable:writable))return;setBusy(true);setError('');try{await work();await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Check your connection and retry.');}finally{setBusy(false);}}
 function edit(item:Compliance|null){setEditing(item);setLabel(item?.label??'');setDate(item?.due_date??'');setDays(item?.lead_days.join(', ')??'30, 7');setAssigned(item?.notify_assigned??false);setRemove(false);}
 async function saveCompliance(archive=false){await run(async()=>{
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Enter the due date as YYYY-MM-DD.');
  const lead=days.trim()?days.split(',').map(d=>Number(d.trim())):[];if(lead.some(n=>!Number.isInteger(n)||n<0))throw Error('Enter reminder days as whole numbers separated by commas.');
  const result=await rpc<{status:string}>('save_compliance',{p_id:editing?.id??null,p_asset:assetId,p_label:label,p_due:date,p_lead_days:lead,p_notify_assigned:assigned,p_revision:editing?.revision??0,p_archived:archive});if(result.status==='conflict')throw Error('This item changed. Cancel, refresh and reopen it.');setEditing(undefined);
 });}
 return <View style={{gap:18}}><PendingSync/>
  {loading?<ActivityIndicator/>:null}{error?<Text accessibilityLiveRegion="polite" style={{color:'#A23D37'}}>{error}</Text>:null}
  <Text style={{fontSize:21,fontWeight:'700',color:'#153C32'}}>Issues</Text>
  {!issues.length&&!loading?<Text>No issues reported.</Text>:null}
  {issues.map(issue=><View key={issue.id} style={card}><Pressable accessibilityRole="button" onPress={()=>setExpanded(expanded===issue.id?null:issue.id)}><Text style={{fontWeight:'700',color:issue.urgency==='Urgent'?'#A23D37':'#153C32'}}>{issue.urgency} · {issue.resolutions.length?'Resolved':'Open'}</Text><Text>{issue.description}</Text></Pressable>{expanded===issue.id?<><Text>Reported by {issue.performer_name}</Text><Text>Captured {new Date(issue.capture_time).toLocaleString()}</Text><Text>Received {new Date(issue.server_time).toLocaleString()}</Text>{issue.resolutions.map(r=><View key={r.id} style={{gap:5}}><Text>{r.notes}</Text><Text>{new Date(r.server_time).toLocaleString()}</Text></View>)}{admin?<Button label={issue.resolutions.length?'Add resolution note':'Resolve issue'} press={()=>{setResolution(issue.id);setNotes('');resolutionId.current=null;}} disabled={!writable||busy}/>:null}</>:null}
   {resolution===issue.id?<><Field label="Resolution notes" value={notes} set={v=>{setNotes(v);resolutionId.current=null;}}/><Button label="Save resolution" disabled={!writable||busy||!notes.trim()} press={()=>void run(async()=>{resolutionId.current??=Crypto.randomUUID();await rpc('resolve_issue',{p_id:resolutionId.current,p_issue:issue.id,p_notes:notes});setResolution(null);})}/><Button label="Cancel resolution" press={()=>setResolution(null)} disabled={busy}/></>:null}
  </View>)}
  {reporting?<View style={card}><Text style={{fontWeight:'700'}}>Report an issue</Text><View style={{flexDirection:'row',gap:8}}>{['Minor','Attention','Urgent'].map(level=><Pressable key={level} accessibilityRole="radio" accessibilityState={{checked:urgency===level}} onPress={()=>{setUrgency(level);submission.current=null;}} style={{padding:12,borderRadius:10,backgroundColor:urgency===level?'#DDEBDD':'#F5F6F0'}}><Text>{level}</Text></Pressable>)}</View><Field label="What happened?" value={description} set={v=>{setDescription(v);submission.current=null;}}/><Button label={busy?'Saving…':'Save issue'} disabled={busy||!captureWritable||!description.trim()} press={()=>void run(async()=>{submission.current??={id:Crypto.randomUUID(),capture:new Date().toISOString()};await queueEntry({id:submission.current.id,kind:'issue',assetId,label:urgency+' issue',args:{p_id:submission.current.id,p_asset:assetId,p_urgency:urgency,p_description:description,p_capture_time:submission.current.capture}});setReporting(false);void flushQueue();},true)}/><Button label="Cancel issue" disabled={busy} press={()=>setReporting(false)}/></View>:<Button label="Report an issue" disabled={busy||!captureWritable} press={()=>{setReporting(true);setDescription('');setUrgency('Attention');submission.current=null;}}/>}
  <Text style={{fontSize:21,fontWeight:'700',color:'#153C32'}}>Compliance dates</Text>
  {!items.filter(i=>i.archived===archives).length&&!loading?<Text>{archives?'No archived compliance items.':'No compliance dates added yet.'}</Text>:null}
  {items.filter(i=>i.archived===archives).map(item=><View key={item.id} style={card}><Pressable accessibilityRole="button" onPress={()=>setExpanded(expanded===item.id?null:item.id)}><Text style={{fontWeight:'700'}}>{item.label}</Text><Text>Due {item.due_date}{item.days_remaining<0?` · ${-item.days_remaining} days overdue`:item.days_remaining===0?' · Due today':` · ${item.days_remaining} days remaining`}</Text></Pressable>{expanded===item.id?<><Text>Reminders: {item.lead_days.length?item.lead_days.join(', ')+' days before due':'none'}</Text><Text>Recipients: admins{item.notify_assigned?' and assigned technicians':''}</Text>{admin?<Button label="Edit or renew" disabled={busy||!writable} press={()=>edit(item)}/>:null}</>:null}</View>)}
  {admin?<DetailTile initiallyOpen={editing!==undefined} title="Manage compliance" description="Add dates, renewals and reminder settings"><Button label={archives?'Show active compliance items':'Show archived compliance items'} press={()=>setArchives(!archives)}/>{editing===undefined?<Button label="Add compliance date" press={()=>edit(null)} disabled={busy||!writable}/>:<View style={card}><Field label="Compliance name (e.g. WOF, Rego, insurance)" value={label} set={setLabel}/><DateField label="Due date" value={date} onChange={setDate}/><Field label="Reminder days before due (comma separated)" value={days} set={setDays}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:assigned}} onPress={()=>setAssigned(!assigned)}><Text>{assigned?'✓':'□'} Also remind assigned technicians</Text></Pressable><Button label={editing?.archived?'Save and restore':'Save compliance date'} disabled={busy||!writable||!label.trim()} press={()=>void saveCompliance()}/><Button label="Cancel edit" press={()=>setEditing(undefined)} disabled={busy}/>{editing&&!editing.archived?<>{remove?<Button label="Confirm archive (history is kept)" press={()=>void saveCompliance(true)} disabled={busy||!writable}/>:<Button label="Archive compliance item" press={()=>setRemove(true)} disabled={busy||!writable}/>}</>:null}</View>}</DetailTile>:null}
  <Button label="Refresh issues and compliance" press={()=>void load()} disabled={loading||busy}/>
 </View>;
}
