import React,{useState,useEffect} from 'react';
import {View,Text,TextInput,Pressable,ThemeContext,resolveTheme,type ThemeName} from './brandUI';
import Slider from '@react-native-community/slider';
import {hexToHsv,hsvToHex,normalizeHex} from './brandColour';
export function ColourPicker({value,onChange,disabled,onValidityChange}:{value:ThemeName;onChange:(v:ThemeName)=>void;disabled:boolean;onValidityChange:(valid:boolean)=>void}){
 const [mode,setMode]=useState<'wheel'|'hex'>('wheel'),[draft,setDraft]=useState(resolveTheme(value).brand),[hue,setHue]=useState(hexToHsv(resolveTheme(value).brand).h);
 useEffect(()=>onValidityChange(mode==='wheel'||normalizeHex(draft)!==null),[mode,draft,onValidityChange]);
 const hex=resolveTheme(value).brand,hsv=hexToHsv(hex),h=hsv.s?hsv.h:hue;
 function choose(next:string){const valid=normalizeHex(next);if(valid){setDraft(valid);onChange(valid as ThemeName);}}
 function point(x:number,y:number){if(disabled)return;const angle=(Math.atan2(x-130,130-y)*180/Math.PI+360)%360;setHue(angle);choose(hsvToHex(angle,hsv.s||1,hsv.v||1));}
 return <ThemeContext.Provider value="forest"><View style={{gap:14}}><View style={{flexDirection:'row',gap:10}}>{(['wheel','hex'] as const).map(m=><Pressable key={m} accessibilityRole="tab" accessibilityState={{selected:mode===m}} onPress={()=>{setDraft(hex);setMode(m);}} style={{flex:1,padding:14,borderRadius:12,backgroundColor:mode===m?'#EAF0E7':'#FFFFFF',borderWidth:1,borderColor:'#DFE5DC'}}><Text style={{textAlign:'center',fontWeight:'700'}}>{m==='wheel'?'Colour wheel':'HEX code'}</Text></Pressable>)}</View>
 {mode==='hex'?<><Text>Paste your brand colour</Text><TextInput accessibilityLabel="Brand HEX code" autoCapitalize="characters" autoCorrect={false} maxLength={7} editable={!disabled} value={draft} onChangeText={text=>{setDraft(text);const valid=normalizeHex(text);if(valid)onChange(valid as ThemeName);}} onBlur={()=>{const valid=normalizeHex(draft);if(valid)choose(valid);}} placeholder="#147D92" style={{padding:16,fontSize:22,borderWidth:1,borderColor:'#CBD6CC',borderRadius:12}}/>{!normalizeHex(draft)?<Text accessibilityLiveRegion="polite">Enter 3 or 6 HEX digits, such as #147D92.</Text>:null}</>:<>
 <View style={{width:260,height:260,borderRadius:130,overflow:'hidden',alignSelf:'center',backgroundColor:'#FFFFFF'}} accessibilityRole="adjustable" accessibilityLabel="Brand colour wheel" accessibilityValue={{min:0,max:359,now:Math.round(h),text:hex}} accessibilityActions={[{name:'increment'},{name:'decrement'}]} onAccessibilityAction={e=>{if(disabled)return;const next=(h+(e.nativeEvent.actionName==='increment'?5:355))%360;setHue(next);choose(hsvToHex(next,hsv.s||1,hsv.v||1));}} onStartShouldSetResponder={()=>!disabled} onMoveShouldSetResponder={()=>!disabled} onResponderGrant={e=>point(e.nativeEvent.locationX,e.nativeEvent.locationY)} onResponderMove={e=>point(e.nativeEvent.locationX,e.nativeEvent.locationY)}>
 {Array.from({length:72},(_,i)=><View key={i} pointerEvents="none" style={{position:'absolute',width:260,height:260,transform:[{rotate:`${i*5}deg`}]}}><View style={{position:'absolute',left:124,top:0,width:0,height:0,borderLeftWidth:6,borderRightWidth:6,borderTopWidth:132,borderLeftColor:'transparent',borderRightColor:'transparent',borderTopColor:hsvToHex(i*5,1,1)}}/></View>)}
 <View pointerEvents="none" style={{position:'absolute',left:67,top:67,width:126,height:126,borderRadius:63,backgroundColor:hex,borderWidth:6,borderColor:'white'}}/>
 <View pointerEvents="none" style={{position:'absolute',left:121+105*Math.sin(h*Math.PI/180),top:121-105*Math.cos(h*Math.PI/180),width:18,height:18,borderRadius:9,borderWidth:3,borderColor:'white',backgroundColor:hsvToHex(h,1,1)}}/>
 </View><Text>Saturation · {Math.round(hsv.s*100)}%</Text><Slider accessibilityLabel="Colour saturation" minimumValue={0} maximumValue={1} step={.01} value={hsv.s} disabled={disabled} onValueChange={s=>choose(hsvToHex(h,s,hsv.v))} style={{height:44}}/><Text>Brightness · {Math.round(hsv.v*100)}%</Text><Slider accessibilityLabel="Colour brightness" minimumValue={0} maximumValue={1} step={.01} value={hsv.v} disabled={disabled} onValueChange={v=>choose(hsvToHex(h,hsv.s,v))} style={{height:44}}/>
 <Text>Quick colours</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{Array.from({length:36},(_,i)=>hsvToHex((i%12)*30,[.9,.6,.3][Math.floor(i/12)],.8)).map(c=><Pressable key={c} accessibilityRole="button" accessibilityLabel={'Choose '+c} disabled={disabled} onPress={()=>choose(c)} style={{width:44,height:44,padding:5}}><View style={{flex:1,borderRadius:10,backgroundColor:c,borderWidth:hex===c?3:1,borderColor:hex===c?'#111111':'#FFFFFF'}}/></Pressable>)}</View></>}
 <Text style={{fontWeight:'700'}}>Selected colour: {hex}</Text><Text style={{fontSize:13}}>Your exact colour is kept. Text and softer shades are adjusted for readability.</Text></View></ThemeContext.Provider>;
}
