import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from './brandUI';
import type {Asset} from '@klever/domain';
import {rpc} from './client';
type Family={family_key:string;family_name:string;engine_maintenance_note?:string;service_types:{name:string;trigger_mode:string;interval_hours:number|null;interval_days:number|null;instructions:string;recommended_note:string}[]};
type Library={catalog:{brands:{brand:string;families:Family[]}[];model_index:{model:string;brand:string;family_key:string}[]};applied:{model:string;note:string}|null};
export function StarterLibrary({asset,writable,onApplied}:{asset:Asset;writable:boolean;onApplied:()=>void}){
 const [data,setData]=useState<Library|null>(null),[error,setError]=useState(''),[open,setOpen]=useState(false),[model,setModel]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;rpc<Library>('get_starter_library',{p_asset:asset.id}).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[asset.id]);
 const selected=data?.catalog.model_index.find(m=>m.model===model),family=data?.catalog.brands.flatMap(b=>b.families).find(f=>f.family_key===selected?.family_key);
 async function apply(){if(busy||!writable||!confirmed)return;setBusy(true);setError('');try{await rpc('apply_starter_library',{p_asset:asset.id,p_model:model,p_confirmed:confirmed});setData(await rpc<Library>('get_starter_library',{p_asset:asset.id}));onApplied();}catch(e){setError(e instanceof Error?e.message:'Unable to apply the library. Try again.');}finally{setBusy(false);}}
 const button=(label:string,press:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={press} style={{padding:14,backgroundColor:'#EAF0E7',borderRadius:12,opacity:disabled?.4:1}}><Text style={{color:'#153C32',fontWeight:'600'}}>{label}</Text></Pressable>;
 return <View style={{gap:12}}>{button('Truckmount starter library',()=>setOpen(!open))}{open?<>
 {error?<Text style={{color:'#A23D37'}}>{error}</Text>:null}{!data&&!error?<ActivityIndicator/>:null}
 {data?.applied?<><Text>Applied for {data.applied.model}. Services and daily tasks are editable below.</Text><Text>{data.applied.note}</Text><Text>Applying a template again will not overwrite your changes. Use the service and task editors to make adjustments.</Text></>:asset.meter_unit==='km'?<Text>These truckmount templates use hours. Set up services manually for a kilometre asset.</Text>:<>
 <Text>Editable starter guidance, not a verified complete manufacturer schedule. Check the instructions for your exact machine before relying on it.</Text>
 {data?.catalog.brands.map(brand=><View key={brand.brand} style={{gap:8}}><Text style={{fontWeight:'700'}}>{brand.brand}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{data.catalog.model_index.filter(m=>m.brand===brand.brand).map(m=><Pressable key={m.model} accessibilityRole="radio" accessibilityState={{checked:model===m.model}} onPress={()=>{setModel(m.model);setConfirmed(false);}} style={{padding:12,borderRadius:10,borderWidth:1,borderColor:model===m.model?'#226A50':'#DFE5DC',backgroundColor:model===m.model?'#DDEBDD':'white'}}><Text>{m.model}</Text></Pressable>)}</View></View>)}
 {family?<View style={{gap:10}}><Text style={{fontWeight:'700'}}>Services to add</Text>{family.service_types.map(s=><View key={s.name} style={{gap:5}}><Text>{s.name}</Text><Text>{s.interval_hours?`${s.interval_hours} hours`:''}{s.trigger_mode==='both'?' or ':''}{s.interval_days?`${s.interval_days} days`:''}</Text><Text>{s.instructions}</Text>{s.recommended_note?<Text>{s.recommended_note}</Text>:null}</View>)}<Text>Also adds daily startup and end-of-day checklists. Enter your last-service baselines in the service schedules after applying.</Text>{family.engine_maintenance_note?<Text>{family.engine_maintenance_note.replace(' (odometer tracking is a Phase 2 feature)','')}</Text>:null}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:confirmed}} onPress={()=>setConfirmed(!confirmed)} style={{paddingVertical:12}}><Text>{confirmed?'✓':'□'} I will review this starter guidance against my machine instructions</Text></Pressable>{button(busy?'Applying…':'Add services and daily tasks',()=>void apply(),busy||!confirmed||!writable)}</View>:null}
 </>}
 </>:null}</View>;
}
