import type {Asset} from '@klever/domain';
export type ServiceSummary={id:string;config:{name:string;meter_unit:string};due:boolean;missing_baseline:boolean;unit_mismatch:boolean;remaining:number|null;next_date:string|null};
export type TaskSummary={id:string;due:boolean;can_complete:boolean;next_due:string;config:{name:string}};
export type AssetSummary={id:string;services:ServiceSummary[];tasks:TaskSummary[];open_issues:number;reading_due:boolean};
export type Overview={assets:AssetSummary[];tasks:TaskSummary[];as_of:string};
export function serviceSummary(row?:AssetSummary){if(!row)return 'Loading service schedule…';const due=row.services.filter(s=>s.due&&!s.missing_baseline&&!s.unit_mismatch).length;if(due)return `${due} service${due===1?'':'s'} due`;if(row.services.some(s=>s.missing_baseline||s.unit_mismatch))return 'Service setup needs attention';const next=row.services.filter(s=>s.remaining!==null&&s.remaining>0).sort((a,b)=>a.remaining!-b.remaining!)[0];if(next)return `Next service in ${Number(next.remaining!.toFixed(1))} ${next.config.meter_unit}`;const date=row.services.map(s=>s.next_date).filter((d):d is string=>!!d).sort()[0];return date?`Next service ${date}`:row.services.length?'No service due':'No services set up';}
export function taskSummary(row?:AssetSummary){if(!row)return 'Loading tasks…';const due=row.tasks.filter(t=>t.due).length;return due?`${due} task${due===1?'':'s'} due`:row.tasks.length?'Tasks up to date':'No tasks set up';}
export type Attention={key:string;title:string;detail:string;kind:'hour_log'|'task_due'|'service_due';assetId?:string;recordId?:string};
export function attentionItems(overview:Overview|undefined,assets:Asset[]):Attention[]{if(!overview)return [];const result:Attention[]=[];for(const row of overview.assets){const asset=assets.find(a=>a.id===row.id&&!a.archived);if(!asset)continue;for(const s of row.services.filter(s=>s.due&&!s.missing_baseline&&!s.unit_mismatch))result.push({key:'s'+asset.id+s.id,title:s.config.name,detail:asset.name+' · Service due',kind:'service_due',assetId:asset.id,recordId:s.id});for(const t of row.tasks.filter(t=>t.due))result.push({key:'t'+t.id,title:t.config.name,detail:asset.name+' · Task due',kind:'task_due',assetId:asset.id,recordId:t.id});if(row.reading_due)result.push({key:'r'+asset.id,title:`Record ${asset.meter_unit}`,detail:asset.name+' · Reading due',kind:'hour_log',assetId:asset.id});}for(const t of overview.tasks.filter(t=>t.due))result.push({key:'t'+t.id,title:t.config.name,detail:'Company task',kind:'task_due',recordId:t.id});return result;}
