// Run only against the explicitly selected development project. Keys stay in memory.
import {randomUUID,randomBytes} from 'node:crypto';
import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const base=process.env.EXPO_PUBLIC_SUPABASE_URL;
const admin=process.env.KLEVER_ADMIN_KEY;
const pub=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
if(base!=='https://blzubtujrxpcnfphcrny.supabase.co'||!admin||!pub)throw Error('Explicit development connection required');
const users=[],tenants=[],photos=[];
async function request(path,{token=admin,method='GET',body,allowError=false,contentType='application/json'}={}){
  const r=await fetch(base+path,{method,headers:{apikey:pub,Authorization:`Bearer ${token}`,'Content-Type':contentType,'cache-control':contentType==='image/jpeg'?'max-age=0':'no-store'},body:body===undefined?undefined:body instanceof Uint8Array?body:JSON.stringify(body)});
  const data=await r.json().catch(()=>null);
  if(!r.ok&&!allowError)throw Error(`${method} ${path.split('?')[0]} failed (${r.status}): ${data?.message??data?.msg??data?.error_description??'request rejected'}`);
  return {ok:r.ok,data};
}
const rpc=async(name,body,token)=> (await request('/rest/v1/rpc/'+name,{method:'POST',body,token})).data;
const stamp=randomUUID();
async function user(label){
  const email=`klever-test-${stamp}-${label}@example.invalid`,password=randomBytes(30).toString('base64url');
  const {data}=await request('/auth/v1/admin/users',{method:'POST',body:{email,password,email_confirm:true}});
  users.push(data.id);
  const login=async()=> (await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},token:pub})).data;
  return {id:data.id,login,...await login()};
}
let passed=0;
const pass=message=>{passed++;console.log(`PASS ${message}`);};
try{
  const a=await user('owner-a'),b=await user('owner-b'),tech=await user('tech'),tech2=await user('tech-two');
  for(const [u,label] of [[a,'A'],[b,'B']])tenants.push(await rpc('provision_business',{p_owner:u.id,p_name:`TEST ONLY ${stamp} ${label}`,p_owner_name:'Test owner',p_write_until:new Date(Date.now()+3600000).toISOString()}));
  await rpc('provision_staff',{p_tenant:tenants[0],p_user:tech.id,p_name:'Test technician'});
  await rpc('provision_staff',{p_tenant:tenants[0],p_user:tech2.id,p_name:'Second test technician'});
  await rpc('save_staff_details',{p_user:tech.id,p_name:'Updated test technician',p_phone:'+64 21 555 0199'},a.access_token);
  const profile=(await request('/rest/v1/memberships?select=name,phone&user_id=eq.'+tech.id,{token:a.access_token})).data[0];
  assert.equal(profile.phone,'+64 21 555 0199');assert.equal(profile.name,'Updated test technician');pass('Admin can edit staff name and phone');
  const typeA=await rpc('save_asset_type',{p_name:'Test type'},a.access_token),typeB=await rpc('save_asset_type',{p_name:'Test type'},b.access_token);
  const assetA=await rpc('save_asset',{p_name:'Assigned test asset',p_type:typeA,p_initial_hours:1240,p_meter_unit:'km'},a.access_token);
  const unassignedAsset=await rpc('save_asset',{p_name:'Unassigned test asset',p_type:typeA},a.access_token);
  const assetB=await rpc('save_asset',{p_name:'Other business test asset',p_type:typeB},b.access_token);
  await rpc('assign_asset',{p_asset:assetA,p_user:tech.id,p_assigned:true},a.access_token);
  const serviceResult=await rpc('save_service_schedule',{p_asset:assetA,p_config:{name:'Test scheduled service',instructions:'Synthetic service instructions',mode:'meter',meter_unit:'km',interval_reading:100,interval_days:null},p_scope:'asset',p_baseline_reading:1200,p_baseline_kind:'last_service'},a.access_token);
  assert.equal(serviceResult.status,'accepted');
  let schedule=(await rpc('list_asset_services',{p_asset:assetA},tech.access_token))[0];
  assert.equal(schedule.remaining,60);assert.equal(schedule.next_reading,1300);assert.equal(schedule.due,false);
  assert.equal((await request('/rest/v1/rpc/list_asset_services',{method:'POST',token:b.access_token,body:{p_asset:assetA},allowError:true})).ok,false);pass('Service baseline arithmetic and cross-business schedule protection');
  const rows=await request('/rest/v1/assets?select=id,meter_unit',{token:tech.access_token});
  assert.deepEqual(rows.data.map(x=>x.id),[assetA]);assert.equal(rows.data[0].meter_unit,'km');pass('Technician sees only the assigned asset across two businesses');
  assert.deepEqual((await request('/rest/v1/tenants?select=id',{token:tech.access_token})).data,[]);pass('Technician cannot read admin business settings');
  assert.equal((await request('/rest/v1/rpc/assign_asset',{method:'POST',token:a.access_token,body:{p_asset:assetB,p_user:tech.id,p_assigned:true},allowError:true})).ok,false);pass('Cross-business writes rejected');
  assert.equal((await request('/rest/v1/assets',{method:'POST',token:tech.access_token,body:{tenant_id:tenants[0],asset_type_id:typeA,name:'Forbidden'},allowError:true})).ok,false);pass('Direct client writes rejected');
  const reading={p_id:randomUUID(),p_asset:assetA,p_value:1241,p_expected_revision:0,p_capture_time:new Date().toISOString()};
  assert.equal((await rpc('log_hours',reading,tech.access_token)).status,'accepted');
  assert.equal((await rpc('log_hours',reading,tech.access_token)).duplicate,true);assert.equal((await request('/rest/v1/hour_logs?select=meter_unit',{token:tech.access_token})).data[0].meter_unit,'km');pass('Real HTTP kilometre readings retain units and retries are accepted once');
  assert.equal((await rpc('log_hours',{...reading,p_id:randomUUID(),p_value:1242},tech.access_token)).status,'conflict');pass('Stale reading rejected without replacing hours');
  assert.deepEqual((await request('/rest/v1/hour_logs?select=id',{token:b.access_token})).data,[]);pass('Evidence isolated between businesses');
  assert.equal((await request('/storage/v1/object/evidence/unauthorized.jpg',{method:'POST',token:tech.access_token,contentType:'image/jpeg',body:readFileSync('tmp/service-test.jpg'),allowError:true})).ok,false);pass('Unauthorized evidence upload rejected');
  const photoId=randomUUID();schedule=(await rpc('list_asset_services',{p_asset:assetA},tech.access_token))[0];
  const reservation=await rpc('prepare_service_photo',{p_id:photoId,p_asset:assetA,p_service:serviceResult.id,p_reading:1241,p_capture_time:new Date().toISOString(),p_snapshot:schedule.config,p_settings_revision:schedule.settings_revision},tech.access_token);
  photos.push(reservation.path);
  assert.equal((await request('/rest/v1/rpc/complete_service',{method:'POST',token:tech.access_token,body:{p_id:photoId},allowError:true})).ok,false);
  await request('/storage/v1/object/evidence/'+reservation.path,{method:'POST',token:tech.access_token,contentType:'image/jpeg',body:readFileSync('tmp/service-test.jpg')});
  assert.equal((await rpc('complete_service',{p_id:photoId},tech.access_token)).status,'applied');
  assert.equal((await rpc('complete_service',{p_id:photoId},tech.access_token)).duplicate,true);
  assert.equal((await rpc('list_asset_services',{p_asset:assetA},tech.access_token))[0].remaining,100);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:photoId},token:tech.access_token})).ok,true);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:photoId},token:b.access_token,allowError:true})).ok,false);
  assert.equal((await request('/storage/v1/object/evidence/'+reservation.path,{method:'PUT',token:tech.access_token,contentType:'image/jpeg',body:readFileSync('tmp/service-test.jpg'),allowError:true})).ok,false);
  pass('Real JPEG upload required, service completion idempotent, next threshold reset and photo private/immutable');
  schedule=(await rpc('list_asset_services',{p_asset:assetA},a.access_token))[0];
  const correction={p_id:randomUUID(),p_history:photoId,p_action:'replace',p_reason:'Synthetic admin correction',p_baseline_reading:1240,p_baseline_date:null,p_settings_revision:schedule.settings_revision,p_confirmed:true};
  assert.equal((await rpc('correct_service',correction,a.access_token)).status,'accepted');
  assert.equal((await rpc('correct_service',correction,a.access_token)).duplicate,true);
  const correctedHistory=(await rpc('list_service_history',{p_asset:assetA,p_service:serviceResult.id},tech.access_token))[0];
  assert.equal(correctedHistory.reading,1241);assert.equal(correctedHistory.corrections.length,1);assert.equal(correctedHistory.corrections[0].baseline_reading,1240);
  pass('Admin service correction preserves original evidence and retries safely');
  const edit={p_asset:assetA,p_name:'Corrected test asset',p_type:typeA,p_serial:'EDITED',p_meter_unit:'hours',p_reading:100,p_expected_revision:1,p_reason:'Wrong unit selected at setup'};
  assert.equal((await rpc('edit_asset',edit,a.access_token)).status,'confirmation_required');
  assert.equal((await rpc('edit_asset',{...edit,p_confirmed:true},a.access_token)).status,'accepted');
  const corrected=(await request('/rest/v1/assets?select=name,serial,meter_unit,current_hours&id=eq.'+assetA,{token:a.access_token})).data[0];
  schedule=(await rpc('list_asset_services',{p_asset:assetA},a.access_token))[0];assert.equal(schedule.unit_mismatch,true);assert.equal(schedule.baseline_reading,null);assert.equal(corrected.name,'Corrected test asset');assert.equal(corrected.serial,'EDITED');assert.equal(corrected.meter_unit,'hours');assert.equal(Number(corrected.current_hours),100);
  assert.equal((await request('/rest/v1/hour_logs?select=meter_unit',{token:tech.access_token})).data[0].meter_unit,'km');
  assert.equal((await rpc('log_hours',{...reading,p_id:randomUUID(),p_value:1242,p_expected_revision:1},tech.access_token)).status,'conflict');pass('Asset edits and confirmed unit correction preserve old history and reject stale readings');
  const taskConfig={name:'Synthetic shared task',instructions:'Test only',completion_mode:'shared',cadence:'daily',checklist:[{id:'check',label:'Synthetic check'}],photo_required:true,notes_required:true};
  const sharedTask=await rpc('save_task',{p_id:null,p_asset:null,p_config:taskConfig,p_due:'2020-01-01',p_revision:0},a.access_token);
  let task=(await rpc('list_tasks',{},tech.access_token)).items.find(t=>t.id===sharedTask.id);
  const taskPhoto=randomUUID(),taskPrepare={p_id:taskPhoto,p_task:task.id,p_occurrence:task.occurrence_id,p_revision:task.revision,p_snapshot:task.config,p_checked:['check'],p_notes:'Synthetic notes',p_capture_time:new Date().toISOString(),p_photo:true};
  assert.equal((await request('/rest/v1/rpc/prepare_task',{method:'POST',token:tech.access_token,body:{...taskPrepare,p_checked:[]},allowError:true})).ok,false);
  const taskUpload=await rpc('prepare_task',taskPrepare,tech.access_token);photos.push(taskUpload.path);
  assert.equal((await request('/rest/v1/rpc/complete_task',{method:'POST',token:tech.access_token,body:{p_id:taskPhoto},allowError:true})).ok,false);
  await request('/storage/v1/object/evidence/'+taskUpload.path,{method:'POST',token:tech.access_token,contentType:'image/jpeg',body:readFileSync('tmp/service-test.jpg')});
  assert.equal((await rpc('complete_task',{p_id:taskPhoto},tech.access_token)).status,'completed');
  assert.equal((await rpc('complete_task',{p_id:taskPhoto},tech.access_token)).duplicate,true);
  assert.equal((await rpc('prepare_task',{...taskPrepare,p_id:randomUUID()},tech2.access_token)).status,'already_completed');
  assert.equal((await rpc('list_task_history',{p_task:task.id},tech2.access_token)).length,0);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:taskPhoto,kind:'task'},token:tech.access_token})).ok,true);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:taskPhoto,kind:'task'},token:tech2.access_token,allowError:true})).ok,false);
  pass('Shared tasks require checklist and JPEG evidence, close once and keep history actor-private');
  const personalConfig={...taskConfig,completion_mode:'individual',name:'Synthetic wash van',checklist:[],photo_required:false,notes_required:false};
  const individualTask=await rpc('save_task',{p_id:null,p_asset:null,p_config:personalConfig,p_due:'2020-01-01',p_revision:0},a.access_token);
  task=(await rpc('list_tasks',{},tech.access_token)).items.find(t=>t.id===individualTask.id);
  const individualId=randomUUID();await rpc('prepare_task',{...taskPrepare,p_id:individualId,p_task:task.id,p_occurrence:task.occurrence_id,p_revision:task.revision,p_snapshot:task.config,p_checked:[],p_notes:'',p_photo:false},tech.access_token);
  await rpc('complete_task',{p_id:individualId},tech.access_token);
  const othersTask=(await rpc('list_tasks',{},tech2.access_token)).items.find(t=>t.id===individualTask.id);assert.equal(othersTask.next_due,'2020-01-01');
  const progress=(await rpc('list_tasks',{},a.access_token)).items.find(t=>t.id===individualTask.id);assert.equal(progress.participants.length,2);assert.equal(progress.participants.filter(t=>t.due).length,1);assert.equal(progress.can_complete,false);
  assert.equal((await request('/rest/v1/rpc/list_task_history',{method:'POST',body:{p_task:task.id},token:b.access_token,allowError:true})).ok,false);
  pass('Individual tasks advance only the submitting technician and show separate admin progress');
  const voidTask={p_id:randomUUID(),p_completion:individualId,p_reason:'Synthetic correction',p_next_due:'2020-01-01',p_revision:progress.revision,p_confirmed:true};
  assert.equal((await rpc('void_task_completion',voidTask,a.access_token)).status,'saved');assert.equal((await rpc('void_task_completion',voidTask,a.access_token)).duplicate,true);
  assert.equal((await rpc('list_task_history',{p_task:task.id},tech.access_token))[0].correction.reason,'Synthetic correction');
  pass('Task void preserves evidence, reopens the correct technician and retries once');
  const assetPhoto=randomUUID(),newAssetPhoto=randomUUID(),memberPhoto=randomUUID();
  for(const [id,kind,target,revision] of [[assetPhoto,'asset',assetA,0],[newAssetPhoto,'asset',assetA,1],[memberPhoto,'member',tech.id,0]]){
   const path=await rpc('prepare_profile_photo',{p_id:id,p_kind:kind,p_target:target},a.access_token);photos.push(path);
   assert.equal((await request('/rest/v1/rpc/save_profile_photo',{method:'POST',body:{p_kind:kind,p_target:target,p_upload:id,p_revision:revision},token:a.access_token,allowError:true})).ok,false);
   await request('/storage/v1/object/evidence/'+path,{method:'POST',token:a.access_token,contentType:'image/jpeg',body:readFileSync('tmp/service-test.jpg')});
   assert.equal((await rpc('save_profile_photo',{p_kind:kind,p_target:target,p_upload:id,p_revision:revision},a.access_token)).status,'saved');
   assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:id,kind:'profile'},token:tech.access_token})).ok,true);
   assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:id,kind:'profile'},token:b.access_token,allowError:true})).ok,false);
  }
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:assetPhoto,kind:'profile'},token:tech.access_token,allowError:true})).ok,false);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:memberPhoto,kind:'profile'},token:tech2.access_token,allowError:true})).ok,false);
  pass('Asset and staff photos upload privately, replace safely and hide superseded pictures');
  await rpc('save_profile_photo',{p_kind:'asset',p_target:assetA,p_upload:null,p_revision:2},a.access_token);
  assert.equal((await rpc('get_profile_photo',{p_kind:'asset',p_target:assetA},tech.access_token)).id,null);
  assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:newAssetPhoto,kind:'profile'},token:tech.access_token,allowError:true})).ok,false);
  pass('Removing an asset photo withdraws access without changing service or task evidence');
  const applied=await rpc('apply_starter_library',{p_asset:unassignedAsset,p_model:'Titan 425',p_confirmed:true},a.access_token);assert.equal(applied.services,3);assert.equal(applied.tasks,2);
  assert.equal((await rpc('apply_starter_library',{p_asset:unassignedAsset,p_model:'Titan 425',p_confirmed:true},a.access_token)).status,'already_applied');
  assert.equal((await rpc('list_asset_services',{p_asset:unassignedAsset},a.access_token)).length,3);
  pass('Starter library applies services and daily tasks once without duplicate setup');
  const issueId=randomUUID(),issueArgs={p_id:issueId,p_asset:assetA,p_urgency:'Urgent',p_description:'Synthetic issue only',p_capture_time:new Date().toISOString()};
  await rpc('report_issue',issueArgs,tech.access_token);assert.equal((await rpc('report_issue',issueArgs,tech.access_token)).duplicate,true);
  assert.equal((await request('/rest/v1/notification_outbox?source_id=eq.'+issueId+'&select=channel',{token:a.access_token})).data.length,2);
  assert.equal((await request('/rest/v1/notification_outbox?select=id',{token:tech.access_token})).data.length,0);
  await rpc('resolve_issue',{p_id:randomUUID(),p_issue:issueId,p_notes:'Synthetic resolution'},a.access_token);
  const issue=(await rpc('list_asset_issues',{p_asset:assetA},tech.access_token))[0];assert.equal(issue.description,'Synthetic issue only');assert.equal(issue.resolutions.length,1);
  pass('Urgent issue evidence and resolution remain intact; both admin notification channels queued once');
  const compliance=await rpc('save_compliance',{p_id:null,p_asset:assetA,p_label:'Synthetic WOF',p_due:'2027-01-01',p_lead_days:[30,7],p_notify_assigned:false,p_revision:0},a.access_token);
  await rpc('save_compliance',{p_id:compliance.id,p_asset:assetA,p_label:'Synthetic WOF',p_due:'2028-01-01',p_lead_days:[30,7],p_notify_assigned:true,p_revision:1},a.access_token);
  assert.equal((await rpc('list_compliance',{p_asset:assetA},tech.access_token))[0].due_date,'2028-01-01');
  assert.equal((await request('/rest/v1/rpc/list_compliance',{method:'POST',body:{p_asset:assetA},token:b.access_token,allowError:true})).ok,false);
  pass('Compliance renewals update the shared asset while preserving tenant isolation');
  const businessSettings=await rpc('business_settings',{},a.access_token);
  const settingsArgs={p_name:businessSettings.name,p_timezone:businessSettings.timezone,p_lock:false,p_currency:'AUD',p_revision:businessSettings.revision};
  assert.equal(await rpc('save_business_settings',settingsArgs,a.access_token),true);
  assert.equal(await rpc('save_business_settings',{...settingsArgs,p_currency:'NZD'},a.access_token),false);
  assert.equal((await rpc('access_status',{},a.access_token)).reporting_currency,'AUD');
  assert.equal((await rpc('business_settings',{},b.access_token)).currency,'NZD');
  assert.equal((await request('/rest/v1/rpc/business_settings',{method:'POST',body:{},token:tech.access_token,allowError:true})).ok,false);
  pass('Business settings enforce admin access, tenant boundaries and stale-edit protection');
  const exportResponse=await fetch(base+'/functions/v1/export-report',{method:'POST',headers:{apikey:pub,Authorization:'Bearer '+a.access_token,'Content-Type':'application/json'},body:JSON.stringify({kind:'services',assetId:assetA,format:'pdf'})});
  assert.equal(exportResponse.status,200);const pdf=Buffer.from(await exportResponse.arrayBuffer());assert.equal(pdf.subarray(0,5).toString(),'%PDF-');mkdirSync('tmp/pdfs',{recursive:true});writeFileSync('tmp/pdfs/hosted-maintenance.pdf',pdf);pass('Hosted maintenance PDF embeds authorized service evidence');
  assert.equal((await request('/functions/v1/export-report',{method:'POST',token:tech.access_token,body:{kind:'services',assetId:assetA,format:'pdf'},allowError:true})).ok,false);
  assert.equal((await request('/functions/v1/export-report',{method:'POST',token:b.access_token,body:{kind:'services',assetId:assetA,format:'pdf'},allowError:true})).ok,false);pass('Hosted exports deny technicians and cross-business requests');
  await request('/rest/v1/tenants?id=eq.'+tenants[0],{method:'PATCH',body:{write_until:new Date(Date.now()-60000).toISOString()}});
  assert.equal((await request('/functions/v1/export-report',{method:'POST',token:a.access_token,body:{kind:'logs',assetId:assetA,format:'csv'}})).ok,true);
  const readOnlySettings=await rpc('business_settings',{},a.access_token);assert.equal(readOnlySettings.currency,'AUD');
  assert.equal((await request('/rest/v1/rpc/save_business_settings',{method:'POST',body:{...settingsArgs,p_revision:readOnlySettings.revision},token:a.access_token,allowError:true})).ok,false);pass('Read-only settings remain visible and reject edits');
  await request('/rest/v1/tenants?id=eq.'+tenants[0],{method:'PATCH',body:{write_until:new Date(Date.now()+3600000).toISOString()}});pass('Read-only businesses retain hosted export access');
  await rpc('manage_staff',{p_user:tech.id,p_action:'sign_out'},a.access_token);
  assert.equal((await rpc('access_status',{},tech.access_token)).allowed,false);assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:memberPhoto,kind:'profile'},token:tech.access_token,allowError:true})).ok,false);assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:taskPhoto,kind:'task'},token:tech.access_token,allowError:true})).ok,false);assert.equal((await request('/functions/v1/service-photo',{method:'POST',body:{submissionId:photoId},token:tech.access_token,allowError:true})).ok,false);
  assert.deepEqual((await request('/rest/v1/assets?select=id',{token:tech.access_token})).data,[]);
  assert.equal((await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',token:pub,body:{refresh_token:tech.refresh_token},allowError:true})).ok,false);pass('Remote sign-out blocks old JWT data access and refresh token');
  const again=await tech.login();assert.equal((await rpc('access_status',{},again.access_token)).allowed,true);pass('Active technician can log in again');
  await rpc('manage_staff',{p_user:tech.id,p_action:'deactivate'},a.access_token);
  const inactive=await tech.login();assert.equal((await rpc('access_status',{},inactive.access_token)).allowed,false);pass('Deactivated technician denied after a fresh login');
  console.log(`${passed} hosted checks passed.`);
} finally {
  // Exact IDs created by this run only. Deferred owner invariants require one transaction.
  mkdirSync('tmp',{recursive:true});
  const ids=tenants.map(x=>{assert.match(x,/^[a-f0-9-]{36}$/);return `'${x}'`;}).join(',');
  if(ids)writeFileSync('tmp/hosted-smoke-cleanup.sql',`begin;\nupdate public.tenants set write_until=now()-interval '1 day' where id in (${ids});\ndelete from private.service_notification_state where tenant_id in (${ids});\n${['notification_rules','device_tokens','notification_outbox','issue_resolutions','issues','compliance_items','template_applications','profile_photos','profile_photo_uploads','task_corrections','task_completions','task_submissions','task_person_state','tasks','service_corrections','service_admin_details','service_history','service_uploads','asset_service_settings','service_types','hour_logs','asset_history','asset_assignments','assets','asset_types','memberships','tenants'].map(t=>`delete from public.${t} where ${t==='tenants'?'id':'tenant_id'} in (${ids});`).join('\n')}\ncommit;`);
  // Cleanup auth users only after the SQL transaction succeeds; IDs contain no credentials.
  writeFileSync('tmp/hosted-smoke-photos.json',JSON.stringify(photos));
  writeFileSync('tmp/hosted-smoke-users.json',JSON.stringify(users));
  console.log('Exact test-data cleanup manifest written to ignored tmp directory.');
}

