create function public.export_data(p_kind text,p_asset uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare tid uuid:=private.require_access(true,false);result jsonb;begin
 if p_asset is not null and not exists(select 1 from public.assets where id=p_asset and tenant_id=tid) then raise exception 'Asset unavailable' using errcode='42501';end if;
 if p_kind='assets' then
 select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'name',a.name,'serial',a.serial,'type',t.name,'status',a.status,'meter_unit',a.meter_unit,'current_reading',a.current_hours,'archived',a.archived) order by a.name,a.id),'[]') into result from public.assets a join public.asset_types t on t.id=a.asset_type_id where a.tenant_id=tid and (p_asset is null or a.id=p_asset);
 elsif p_kind='logs' then
 select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'asset',a.name,'reading',h.value,'unit',h.meter_unit,'delta',h.delta,'performer',m.name,'capture_time',h.capture_time,'server_time',h.server_time,'correction_of',h.correction_of,'reason',h.reason) order by h.server_time,h.id),'[]') into result from public.hour_logs h join public.assets a on a.id=h.asset_id join public.memberships m on m.user_id=h.logged_by where h.tenant_id=tid and (p_asset is null or h.asset_id=p_asset);
 elsif p_kind='services' then
 select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'asset',u.asset_name,'serial',u.asset_serial,'service',u.snapshot->>'name','instructions',u.snapshot,'reading',u.reading,'unit',u.meter_unit,'performer',u.performer_name,'capture_time',u.capture_time,'server_time',h.server_time,'state',h.state,'photo_path',u.object_path,'cost',ad.cost,'mechanic_notes',ad.mechanic_notes,'corrections',coalesce((select jsonb_agg(jsonb_build_object('action',c.action,'reason',c.reason,'reading',c.baseline_reading,'unit',c.meter_unit,'date',c.baseline_date,'server_time',c.server_time) order by c.server_time,c.id) from public.service_corrections c where c.history_id=h.id),'[]')) order by u.capture_time,h.id),'[]') into result from public.service_history h join public.service_uploads u on u.id=h.id left join public.service_admin_details ad on ad.history_id=h.id where h.tenant_id=tid and (p_asset is null or h.asset_id=p_asset);
 elsif p_kind='tasks' then
 select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'asset',t.asset_name,'task',t.snapshot->>'name','instructions',t.snapshot,'checked_ids',t.checked_ids,'notes',t.notes,'performer',t.performer_name,'capture_time',t.capture_time,'server_time',t.server_time,'due_date',t.due_date,'effective_completion',not exists(select 1 from public.task_corrections c where c.completion_id=t.id),'photo_path',t.object_path,'corrections',coalesce((select jsonb_agg(jsonb_build_object('reason',c.reason,'server_time',c.server_time) order by c.server_time,c.id) from public.task_corrections c where c.completion_id=t.id),'[]')) order by t.capture_time,t.id),'[]') into result from public.task_submissions t where t.tenant_id=tid and exists(select 1 from public.task_completions cc where cc.id=t.id) and (p_asset is null or t.asset_id=p_asset);
 else raise exception 'Choose assets, logs, services or tasks';end if;
 return jsonb_build_object('kind',p_kind,'business',(select name from public.tenants where id=tid),'timezone',(select timezone from public.tenants where id=tid),'generated_at',now(),'asset',(select jsonb_build_object('name',name,'serial',serial,'meter_unit',meter_unit,'current_reading',current_hours) from public.assets where id=p_asset and tenant_id=tid),'rows',result);
end$$;
revoke execute on function public.export_data(text,uuid) from public,anon,authenticated;
grant execute on function public.export_data(text,uuid) to authenticated;
